# Generated by Django 4.0.5 on 2022-07-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='education_form',
            field=models.CharField(choices=[('budget', 'budget'), ('contract', 'contract')], max_length=100),
        ),
    ]
