# Generated by Django 4.0.5 on 2022-07-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_student_education_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('W', 'W')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_form',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Extramural', 'Extramural')], max_length=100),
        ),
    ]
