# Generated by Django 4.0.5 on 2022-07-04 20:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lesson_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='lesson_files_upload', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'pptx', 'xls', 'csv'])])),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
            ],
        ),
    ]
